# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 60, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 280, 51, 21))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 90, 191, 81))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.encryptedTextOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.encryptedTextOutput.setGeometry(QtCore.QRect(130, 280, 191, 81))
        self.encryptedTextOutput.setObjectName("encryptedTextOutput")
        self.signatureTextOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.signatureTextOutput.setGeometry(QtCore.QRect(550, 280, 191, 81))
        self.signatureTextOutput.setObjectName("signatureTextOutput")
        self.cipherTextInput = QtWidgets.QTextEdit(self.centralwidget)
        self.cipherTextInput.setGeometry(QtCore.QRect(550, 90, 191, 81))
        self.cipherTextInput.setObjectName("cipherTextInput")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 90, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 280, 61, 21))
        self.label_5.setObjectName("label_5")
        self.generateKeysButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeysButton.setGeometry(QtCore.QRect(40, 20, 81, 23))
        self.generateKeysButton.setObjectName("generateKeysButton")
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setGeometry(QtCore.QRect(240, 390, 75, 23))
        self.decryptButton.setObjectName("decryptButton")
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setGeometry(QtCore.QRect(130, 390, 75, 23))
        self.encryptButton.setObjectName("encryptButton")
        self.signButton = QtWidgets.QPushButton(self.centralwidget)
        self.signButton.setGeometry(QtCore.QRect(550, 390, 75, 23))
        self.signButton.setObjectName("signButton")
        self.verifyButton = QtWidgets.QPushButton(self.centralwidget)
        self.verifyButton.setGeometry(QtCore.QRect(670, 390, 75, 23))
        self.verifyButton.setObjectName("verifyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain text"))
        self.label_3.setText(_translate("MainWindow", "Encrypted"))
        self.label_4.setText(_translate("MainWindow", "information"))
        self.label_5.setText(_translate("MainWindow", "signature"))
        self.generateKeysButton.setText(_translate("MainWindow", "Generate keys"))
        self.decryptButton.setText(_translate("MainWindow", "Decrypt"))
        self.encryptButton.setText(_translate("MainWindow", "Encrypt"))
        self.signButton.setText(_translate("MainWindow", "Sign"))
        self.verifyButton.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
